# fly.toml app configuration file generated for globalapp-nodejs-muddy-resonance-5289 on 2023-12-15T22:30:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "globalapp-nodejs-muddy-resonance-5289"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/data"